channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.2
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.3.2
  - psutil==7.0.0
  - pyarrow==19.0.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
